blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Alfaizkhan/USB-Serial-Communication/tree/main/docs
    about: Read our technical documentation and troubleshooting guides
